### ISSUE TITLE
minimizing the cheat to autobackstab

### ISSUE THREAD

**Issue by fun-res** [Lak3/ProjectIC_TF2#1]
Hi, thank you for the great code!
I have a question, can I clean up all the functionality except the autobackstab trigger, rewrite the code a little, rename the methods and not be seen on faceit, vac?
I have some knowledge of programming, but this is my first time dealing with cheats and I really want to try it. Thanks !

**Comment by Lak3** [comment]
Hey, If you only want the auto-backstab I am quite sure that after removing other features the final binary of the cheat has changed already enough to avoid VAC. Keep in mind that this software uses simple VMT hooks which are detected on CS:GO, so I would not be surprised if Valve added the same detection functionality later on TF2.

But yeah, removing other features should be all gucci to be used. But keep in mind that this source is quite old and there's a lot to improve code wise!
